/** FinSkalp Fusion UI copy — Russian strings for Graph OS surfaces. */
export const fusionCopy = {
  missionControl: {
    objective: 'КОМАНДНЫЙ ЦЕНТР',
    emptyQueueTitle: 'Очередь пуста — нет активного дела',
    emptyQueueDescription: 'Запустите расследование через Collect (⌘K) или откройте очередь дел.',
    collectSeed: 'Collect · Seed',
    queue: 'Очередь',
    caseNotSelected: 'Дело не выбрано',
  },
  investigation: {
    objective: 'РАССЛЕДОВАНИЕ',
    timelineTab: 'Хронология',
    hypothesesTab: 'Гипотезы',
    awaitingTimeline: 'ОЖИДАНИЕ СОБЫТИЙ ХРОНОЛОГИИ',
    noHypotheses: 'НЕТ ГИПОТЕЗ — ЗАПУСТИТЕ FUSION',
    noEvidence: 'НЕТ ДОКАЗАТЕЛЬСТВ',
    selectedNode: 'ВЫБРАННЫЙ УЗЕЛ',
    selectEntityOnGraph: 'Выберите сущность на графе',
    graphNodeLink: '↔ узел графа',
    evidenceLinked: 'Доказательство привязано к графу',
    fusionComplete: 'OSINT Fusion завершён',
    workflowUpdated: 'Workflow обновлён',
    seedSaved: 'Seed и collectors сохранены',
    seedSavedRun: 'Seed сохранён — запуск pipeline',
    runCollectors: 'Запустить collectors',
    seedRequired: 'Укажите seed (кошелёк или объект) — откроется форма Collect',
    pipelineCollectors: 'Сбор Scalpel…',
    pipelineGraph: 'Построение графа…',
    pipelineKyt: 'KYT-скрининг…',
    pipelineDone: 'Pipeline завершён',
    pipelineError: 'Ошибка pipeline расследования',
    pipelineRetry: 'Повторить',
    pipelineFailedCollectors: (n: number) => `${n} collector(s) failed`,
    kytOverlay: (score: number | string, level: string) => `KYT ${score} · ${level}`,
    liveStale: 'Поток: ожидание live-событий',
    liveFresh: (n: number) => `Поток: ${n} diff-событий`,
    phaseNotStarted: 'НЕ НАЧАТО · нет графа',
    phaseCollecting: (n: number) => `СБОР… · ${n} узлов`,
    phaseCollectError: (n: number) => `ОШИБКА СБОРА · ${n} узлов`,
    phaseInProgress: (n: number) => `В ПРОЦЕССЕ · ${n} узлов · fusion не запущен`,
    phaseFusionDone: (n: number) => `FUSION ГОТОВ · ${n} узлов · можно отчёт`,
    phaseHintInProgress:
      'Расследование НЕ закончено. Есть граф — выполните MIO / Fusion, затем откройте Отчёты.',
    phaseHintDone: 'Fusion завершён — отчёты доступны.',
  },
  graph: {
    awaitingIntelTitle: 'Граф ожидает разведданные',
    awaitingIntelDescription:
      'Запустите Collect или выполните миссию MIO (Scalpel / Fusion), чтобы построить сущности и связи.',
    noDataTitle: 'Нет данных графа',
    noDataDescription: 'Откройте дело из очереди или начните расследование через Collect.',
    collectSeed: 'Collect · Seed',
    graphAlerts: (count: number) => `▲ ${count} оповещ. графа`,
  },
  mio: {
    title: 'MIO · Офицер разведки',
    titleShort: 'MIO',
    panelTitle: 'Офицер разведки (MIO)',
    awaitingRecommendations: 'Ожидание рекомендаций — запустите сбор или выберите дело',
    noRecommendationsTitle: 'НЕТ РЕКОМЕНДАЦИЙ',
    noRecommendationsDescription:
      'Ожидание FUSION — офицер разведки предложит действия после анализа дела.',
    missionsSummary: (missions: number, actions: number) =>
      `${missions} миссий · ${actions} действий`,
    execAll: 'ВЫПОЛНИТЬ ВСЕ',
    execAllRunning: 'ВЫПОЛН…',
    execAllCount: (selected: number) => `ВЫПОЛНИТЬ ВСЕ (${selected})`,
    execProgress: (current: number, total: number) => `ВЫПОЛН ${current}/${total}`,
    exec: 'ВЫПОЛНИТЬ',
    defer: 'ОТЛОЖИТЬ',
    dismiss: 'ОТКЛОНИТЬ',
    running: 'ВЫПОЛНЯЕТСЯ',
    readOnly: 'ТОЛЬКО ЧТЕНИЕ',
    readOnlyTitle: 'Роль viewer — EXECUTE отключён',
    viewerBlocked: 'Read-only role — EXECUTE disabled',
    batchComplete: 'Пакет MIO выполнен',
    batchFailed: (count: number) => `${count} миссий не выполнено`,
    batchPartial: (ok: number, fail: number) => `Частично: ${ok} ok, ${fail} fail`,
    batchError: 'Ошибка пакетного выполнения',
    batchCancelled: 'Пакет MIO отменён',
    batchCancel: 'ОТМЕНА',
    confidenceLabel: 'Уверенность MIO',
    consequencePrefix: '→',
    graphDiffApplied: (n: number) => `Граф обновлён: ${n} diff-событий`,
    priority: {
      critical: 'КРИТ',
      high: 'ВЫС',
      medium: 'СР',
      low: 'НИЗ',
    },
    missionLabels: {
      collect: 'МИССИЯ · Сбор',
      kyt: 'МИССИЯ · KYT',
      workflow: 'МИССИЯ · Workflow',
      open_evidence: 'МИССИЯ · Доказательства',
      refresh_graph: 'МИССИЯ · Граф',
      focus_seed: 'МИССИЯ · Seed',
      open_report: 'МИССИЯ · Отчёт',
      run_scalpel: 'МИССИЯ · Scalpel',
      mission: 'МИССИЯ',
    } as Record<string, string>,
  },
  mioBatch: {
    strProbability: 'Вероятность подачи STR',
  },
  queue: {
    title: 'Очередь дел',
    subtitle: (count: number) => `${count} активных · приоритет SLA`,
    emptyTitle: 'Очередь пуста',
    emptyDescription: 'Запустите новое расследование через Collect или ⌘K.',
    collectSeed: 'Collect · Seed',
    emptyDock: 'ОЧЕРЕДЬ ПУСТА',
    slaBreach: 'SLA',
    filterAll: 'Все',
    filterCritical: 'Крит',
    filterNew: 'Новые',
    filterTriage: 'Тriage',
    filterInvestigating: 'В работе',
    filterFiling: 'К подаче',
    triage: 'В работу',
    defer: 'Отложить',
    linkInvestigation: 'Открыть расследование',
  },
  reports: {
    label: 'Отчёты',
    selectCase: 'ВЫБЕРИТЕ ДЕЛО ДЛЯ ОТЧЁТОВ',
    centerTitle: 'Report Center',
    centerSubtitle: 'Financial Intelligence Reporting OS',
    sidebarTitle: 'Reporting OS',
    moduleGrid: 'Report Modules',
    moduleGridTitle: 'Intelligence Report Modules',
    moduleGridDescription:
      'Palantir-grade dossiers generated from live case data — no mock, no placeholders.',
    categories: 'Categories',
    filterAll: 'All',
    presentationMode: 'Presentation Mode',
    openReport: 'Open',
    ready: 'Ready',
    awaitingData: 'Awaiting data',
    unknownModule: 'Unknown report module',
    pdfPreview: 'PDF Preview',
    pdfUnavailable: 'PDF недоступен — завершите Fusion для дела',
    print: 'Print',
    exportHub: 'Export Hub',
    exportHubDescription: 'Скачивание отчётов и пакетов доказательств по реальным API.',
    download: 'Скачать',
    exporting: 'Экспорт…',
    exportReady: 'Экспорт доказательств готов',
    exportFailed: 'Не удалось экспортировать доказательства',
    noCaseId: 'Нет case_id — завершите fusion для дела',
    generatedReports: 'Сгенерированные отчёты',
    loadFailed: 'Не удалось загрузить список отчётов',
    emptyTitle: 'Нет отчётов',
    emptyDescription: 'Завершите расследование (fusion) для генерации отчётов.',
    backToInvestigation: 'Вернуться к расследованию',
    noCasesTitle: 'Нет дел',
    noCasesDescription: 'Запустите расследование через Mission Control или Collect.',
    recentReports: 'Недавние отчёты',
  },
  intelligence: {
    awaitingStream: 'ОЖИДАНИЕ ПОТОКА РАЗВЕДДАННЫХ',
    awaitingLive: 'ОЖИДАНИЕ LIVE-РАЗВЕДДАННЫХ',
  },
  dock: {
    timeline: 'Хронология',
    transactions: 'Транзакции',
    evidence: 'Доказательства',
    osint: 'OSINT',
    wallets: 'Кошельки',
    blockchain: 'Блокчейн',
    reports: 'Отчёты',
    tasks: 'Задачи',
    noTransactionEvents: 'НЕТ СОБЫТИЙ ТРАНЗАКЦИЙ',
    noEvidenceItems: 'НЕТ ДОКАЗАТЕЛЬСТВ',
    noOsintEvidence: 'НЕТ OSINT-ДОКАЗАТЕЛЬСТВ',
    supportedChains: 'ПОДДЕРЖИВАЕМЫЕ СЕТИ',
    graphEdges: 'РЁБРА ГРАФА',
    awaitingTimelineEvents: 'ОЖИДАНИЕ СОБЫТИЙ ХРОНОЛОГИИ',
    noEvidence: 'НЕТ ДОКАЗАТЕЛЬСТВ',
  },
  screening: (score: number, level: string) => `Скрининг ${score}/100 (${level})`,
  brief: {
    ariaLabel: 'Исполнительный брифинг',
    header: 'БРИФИНГ · 30 СЕК',
    title: 'Оперативная сводка',
    whatHappened: 'ЧТО ПРОИЗОШЛО',
    noStreamEvents: 'Нет недавних событий потока',
    mainRisk: 'ГЛАВНЫЙ РИСК',
    entitiesTracked: (n: number) => `${n} сущностей на графе`,
    moneyInMotion: 'ДВИЖЕНИЕ СРЕДСТВ',
    flowOverlayActive: 'Оверлей потоков активен',
    casesNeedingDecision: 'ДЕЛА, ТРЕБУЮЩИЕ РЕШЕНИЯ',
    slaBreach: 'НАРУШЕНИЕ SLA',
    noCriticalQueue: 'Нет критических дел в очереди',
    topMio: 'ГЛАВНАЯ РЕКОМЕНДАЦИЯ MIO',
    noRecommendations: 'Нет рекомендаций',
    exitHint: 'Shift+Alt+E или Esc — выход',
  },
  eccf: {
    chainTitle: 'ECCF · цепочка custody',
    custodyHash: 'Хэш custody',
    steps: {
      new: 'NEW',
      scoring: 'SCORING',
      fusion: 'FUSION',
      graph: 'GRAPH',
      hypotheses: 'HYP',
      evidence: 'EVID',
      review: 'REVIEW',
      recommendation: 'REC',
      filed: 'SAR',
    } as Record<string, string>,
  },
  scrubber: {
    noTemporalAnchors: 'НЕТ ВРЕМЕННЫХ ЯКОРЕЙ — выберите события хронологии',
    initialState: 'НАЧАЛЬНОЕ СОСТОЯНИЕ',
    replayLabel: 'INVESTIGATION REPLAY',
  },
  graphLayers: {
    groupLabel: 'Слои графа',
    entities: 'Сущности',
    transactions: 'Tx',
    risk: 'Риск',
    crossCase: 'Cross-case',
  },
  keyboard: {
    collect: 'Collect / Seed',
    queue: 'Queue lens',
    brief: 'Brief lens',
    canvas: 'Canvas',
  },
  launcher: {
    invalidWallet: 'Укажите корректный адрес кошелька',
    invalidPerson: 'Укажите ФИО (мин. 2 символа)',
    invalidOrg: 'Укажите название организации',
    invalidPool: 'Пул пуст — добавьте строки seed',
    walletHint: 'TRON / ETH / BTC адрес',
    walletInvalidHint: 'Адрес не распознан',
    personHint: 'Фамилия Имя или person:…',
    orgHint: 'organization:…',
    poolHint: 'wallet:… / person:… / org:…',
    launchFailed: 'Не удалось запустить расследование',
    preparing: 'Подготовка…',
    start: 'Запустить расследование',
    enterHint: 'Enter — запуск · Esc — закрыть',
  },
} as const
