import type { ReportCategory, ReportModuleDef, ReportModuleId } from './report-types'

const BASE_SECTIONS = [
  'cover',
  'classification',
  'metadata',
  'case-info',
] as const

function mod(
  partial: Omit<ReportModuleDef, 'category'> & { category?: ReportCategory }
): ReportModuleDef {
  return partial as ReportModuleDef
}

/** Full production catalog — maps to real API-backed sections only */
export const REPORT_MODULES: ReportModuleDef[] = [
  mod({
    id: 'executive-brief',
    label: 'Executive Intelligence Brief',
    labelRu: 'Исполнительный бриф',
    category: 'intelligence',
    description: '30-секундная сводка риска, сети и уверенности для руководства.',
    glyph: '▤',
    requiresAny: ['fusion', 'graph'],
    sections: [...BASE_SECTIONS, 'executive-summary', 'mission-summary', 'sanctions-exposure', 'network-overview', 'risk', 'recommendations', 'signature'],
    pdfExport: true,
    presentation: true,
  }),
  mod({
    id: 'complete-investigation',
    label: 'Complete Investigation Report',
    labelRu: 'Полный отчёт расследования',
    category: 'intelligence',
    description: 'Формальный документ с содержанием, методологией и выводами.',
    glyph: '▣',
    requiresAny: ['fusion'],
    requiresAll: ['case'],
    sections: [...BASE_SECTIONS, 'executive-summary', 'sanctions-exposure', 'attribution-ownership', 'graph-snapshot', 'entity-table', 'timeline', 'evidence', 'appendices', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'evidence-dossier',
    label: 'Evidence Dossier',
    labelRu: 'Досье доказательств',
    category: 'evidence',
    description: 'ECC-каталог артефактов с хешами, источниками и статусами.',
    glyph: '◎',
    requiresAny: ['evidence'],
    sections: [...BASE_SECTIONS, 'evidence', 'chain-of-custody', 'appendices'],
    pdfExport: true,
  }),
  mod({
    id: 'wallet-intelligence',
    label: 'Wallet Intelligence Report',
    labelRu: 'Разведка кошелька',
    category: 'financial',
    description: 'KYT-скрининг, on-chain профиль и контрагенты.',
    glyph: '◇',
    requiresAny: ['kyt', 'graph'],
    sections: [...BASE_SECTIONS, 'wallet-profile', 'attribution-ownership', 'sanctions-exposure', 'relationship-table', 'risk', 'graph-snapshot', 'recommendations'],
    pdfExport: true,
  }),
  mod({
    id: 'money-flow',
    label: 'Money Flow Report',
    labelRu: 'Движение средств',
    category: 'financial',
    description: 'Маршруты и объёмы переводов по графу и fusion bridges.',
    glyph: '⇄',
    requiresAny: ['fusion', 'graph'],
    sections: [...BASE_SECTIONS, 'money-flow', 'sanctions-exposure', 'relationship-table', 'wallet-profile', 'graph-snapshot'],
    pdfExport: true,
  }),
  mod({
    id: 'entity-profile',
    label: 'Entity Intelligence Profile',
    labelRu: 'Профиль сущности',
    category: 'entity',
    description: 'Досье кластера, атрибуция и локальная сеть.',
    glyph: '◉',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'network-overview', 'entity-table', 'relationship-table', 'graph-snapshot', 'risk'],
    pdfExport: true,
  }),
  mod({
    id: 'osint-intelligence',
    label: 'OSINT Intelligence Report',
    labelRu: 'OSINT-разведка',
    category: 'osint',
    description: 'Упоминания, источники и тематические кластеры.',
    glyph: '⎈',
    requiresAny: ['evidence', 'timeline'],
    sections: [...BASE_SECTIONS, 'osint-mentions', 'timeline', 'evidence', 'mission-summary'],
    pdfExport: true,
  }),
  mod({
    id: 'cross-case',
    label: 'Cross Case Analysis',
    labelRu: 'Межделовой анализ',
    category: 'analysis',
    description: 'Общие сущности и связи между делами.',
    glyph: '⊞',
    requiresAny: ['crossCase'],
    sections: [...BASE_SECTIONS, 'network-overview', 'entity-table', 'relationship-table'],
    pdfExport: true,
  }),
  mod({
    id: 'risk-assessment',
    label: 'Risk Assessment Report',
    labelRu: 'Оценка риска',
    category: 'compliance',
    description: 'Матрица риска, история скоринга и рекомендации.',
    glyph: '▲',
    requiresAny: ['fusion', 'riskHistory', 'kyt'],
    sections: [...BASE_SECTIONS, 'risk', 'executive-summary', 'recommendations'],
    pdfExport: true,
  }),
  mod({
    id: 'compliance',
    label: 'Compliance Report',
    labelRu: 'Комплаенс-отчёт',
    category: 'compliance',
    description: 'Статус соответствия и контрольные процедуры.',
    glyph: '✓',
    requiresAny: ['fusion', 'generatedReports'],
    sections: [...BASE_SECTIONS, 'compliance-checklist', 'executive-summary', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'fz115',
    label: '115-FZ Report',
    labelRu: '115-ФЗ',
    category: 'compliance',
    description: 'Структурированная подача по 115-ФЗ (JSON/XML/PDF).',
    glyph: '⚖',
    requiresAny: ['generatedReports', 'fusion'],
    sections: [...BASE_SECTIONS, 'compliance-checklist', 'executive-summary', 'evidence', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'aml',
    label: 'AML Report',
    labelRu: 'AML-отчёт',
    category: 'compliance',
    description: 'AML-типологии и индикаторы из fusion.',
    glyph: '◆',
    requiresAny: ['fusion'],
    sections: [...BASE_SECTIONS, 'risk', 'sanctions-exposure', 'money-flow', 'relationship-table', 'recommendations'],
    pdfExport: true,
  }),
  mod({
    id: 'kyt',
    label: 'KYT Report',
    labelRu: 'KYT-отчёт',
    category: 'financial',
    description: 'Know-Your-Transaction скрининг и exposure.',
    glyph: '⛓',
    requiresAny: ['kyt'],
    sections: [...BASE_SECTIONS, 'wallet-profile', 'sanctions-exposure', 'attribution-ownership', 'money-flow', 'risk', 'recommendations'],
    pdfExport: true,
  }),
  mod({
    id: 'travel-rule',
    label: 'Travel Rule Report',
    labelRu: 'Travel Rule',
    category: 'compliance',
    description: 'Передача данных VASP и контрагентов.',
    glyph: '⇋',
    requiresAny: ['graph', 'fusion'],
    sections: [...BASE_SECTIONS, 'entity-table', 'wallet-profile'],
    pdfExport: true,
  }),
  mod({
    id: 'blockchain-analysis',
    label: 'Blockchain Analysis Report',
    labelRu: 'Блокчейн-анализ',
    category: 'financial',
    description: 'On-chain топология и статистика графа.',
    glyph: '⬡',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'graph-snapshot', 'network-overview', 'entity-table'],
    pdfExport: true,
  }),
  mod({
    id: 'executive-summary',
    label: 'Executive Summary',
    labelRu: 'Исполнительное резюме',
    category: 'intelligence',
    description: 'Краткое резюме для руководства.',
    glyph: '▤',
    requiresAny: ['fusion'],
    sections: [...BASE_SECTIONS, 'executive-summary', 'risk'],
    pdfExport: true,
    presentation: true,
  }),
  mod({
    id: 'analyst-summary',
    label: 'Analyst Summary',
    labelRu: 'Сводка аналитика',
    category: 'intelligence',
    description: 'Рабочая сводка с гипотезами и следующими шагами.',
    glyph: '▥',
    requiresAny: ['case'],
    sections: [...BASE_SECTIONS, 'mission-summary', 'recommendations', 'analyst-notes'],
    pdfExport: true,
  }),
  mod({
    id: 'chain-of-custody',
    label: 'Chain Of Custody Report',
    labelRu: 'Цепочка custody',
    category: 'evidence',
    description: 'ECCF-аудит и история статусов доказательств.',
    glyph: '⛓',
    requiresAny: ['evidence'],
    sections: [...BASE_SECTIONS, 'chain-of-custody', 'evidence', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'timeline',
    label: 'Timeline Report',
    labelRu: 'Хронология',
    category: 'analysis',
    description: 'Временная лента событий расследования.',
    glyph: '▬',
    requiresAny: ['timeline'],
    sections: [...BASE_SECTIONS, 'timeline', 'graph-snapshot'],
    pdfExport: true,
  }),
  mod({
    id: 'network-intelligence',
    label: 'Network Intelligence Report',
    labelRu: 'Сетевая разведка',
    category: 'entity',
    description: 'Статистика сети, кластеры и центральность.',
    glyph: '◇',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'network-overview', 'graph-snapshot', 'entity-table'],
    pdfExport: true,
  }),
  mod({
    id: 'graph-intelligence',
    label: 'Graph Intelligence Report',
    labelRu: 'Граф-разведка',
    category: 'entity',
    description: 'Community detection и топология связей.',
    glyph: '◈',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'graph-snapshot', 'relationship-table', 'network-overview'],
    pdfExport: true,
    presentation: true,
  }),
  mod({
    id: 'cluster',
    label: 'Cluster Report',
    labelRu: 'Кластерный отчёт',
    category: 'entity',
    description: 'Группировка сущностей по kind и связности.',
    glyph: '◫',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'network-overview', 'entity-table'],
    pdfExport: true,
  }),
  mod({
    id: 'attribution',
    label: 'Attribution Report',
    labelRu: 'Атрибуция',
    category: 'entity',
    description: 'Attribution scores из fusion.',
    glyph: '◌',
    requiresAny: ['fusion'],
    sections: [...BASE_SECTIONS, 'attribution-ownership', 'sanctions-exposure', 'entity-table', 'executive-summary'],
    pdfExport: true,
  }),
  mod({
    id: 'relationship',
    label: 'Relationship Report',
    labelRu: 'Отчёт связей',
    category: 'entity',
    description: 'Матрица связей и типы рёбер.',
    glyph: '↔',
    requiresAny: ['graph'],
    sections: [...BASE_SECTIONS, 'relationship-table', 'graph-snapshot'],
    pdfExport: true,
  }),
  mod({
    id: 'case-review',
    label: 'Case Review Report',
    labelRu: 'Обзор дела',
    category: 'analysis',
    description: 'Workflow, SLA и статус pipeline.',
    glyph: '▢',
    requiresAny: ['case'],
    sections: [...BASE_SECTIONS, 'case-info', 'mission-summary', 'timeline'],
    pdfExport: true,
  }),
  mod({
    id: 'recommendation',
    label: 'Recommendation Report',
    labelRu: 'Рекомендации MIO',
    category: 'analysis',
    description: 'Рекомендации workflow и MIO из fusion.',
    glyph: '→',
    requiresAny: ['fusion', 'case'],
    sections: [...BASE_SECTIONS, 'recommendations', 'executive-summary'],
    pdfExport: true,
  }),
  mod({
    id: 'str',
    label: 'STR Report',
    labelRu: 'STR / Подозрительная операция',
    category: 'compliance',
    description: 'Suspicious Transaction Report — формальная подача.',
    glyph: '⚠',
    requiresAny: ['fusion', 'generatedReports'],
    sections: [...BASE_SECTIONS, 'executive-summary', 'evidence', 'compliance-checklist', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'sar',
    label: 'SAR Report',
    labelRu: 'SAR',
    category: 'compliance',
    description: 'Suspicious Activity Report из investigate pipeline.',
    glyph: '⚠',
    requiresAny: ['fusion'],
    sections: [...BASE_SECTIONS, 'executive-summary', 'risk', 'evidence', 'signature'],
    pdfExport: true,
  }),
  mod({
    id: 'pdf-preview',
    label: 'PDF Preview',
    labelRu: 'Предпросмотр PDF',
    category: 'export',
    description: 'Интерактивный просмотр сгенерированного PDF.',
    glyph: '▣',
    requiresAny: ['fusion', 'generatedReports'],
    sections: ['cover', 'export-actions'],
    pdfExport: true,
  }),
  mod({
    id: 'presentation-mode',
    label: 'Investigation Presentation Mode',
    labelRu: 'Режим презентации',
    category: 'export',
    description: 'Wide-screen briefing для руководства.',
    glyph: '▶',
    requiresAny: ['graph', 'fusion'],
    sections: ['cover', 'executive-summary', 'graph-snapshot', 'network-overview', 'risk'],
    presentation: true,
  }),
  mod({
    id: 'export-center',
    label: 'Export Center',
    labelRu: 'Центр экспорта',
    category: 'export',
    description: 'PDF, XLSX, JSON, GraphML, evidence package.',
    glyph: '⬇',
    requiresAny: ['case'],
    sections: ['export-actions'],
  }),
]

export const REPORT_CATEGORIES: Array<{ id: ReportCategory; label: string }> = [
  { id: 'intelligence', label: 'Intelligence' },
  { id: 'evidence', label: 'Evidence' },
  { id: 'financial', label: 'Financial' },
  { id: 'entity', label: 'Entity' },
  { id: 'osint', label: 'OSINT' },
  { id: 'compliance', label: 'Compliance' },
  { id: 'analysis', label: 'Analysis' },
  { id: 'export', label: 'Export' },
]

export function reportModule(id: ReportModuleId | string): ReportModuleDef | undefined {
  const normalized = String(id).replace(/_/g, '-') as ReportModuleId
  return REPORT_MODULES.find((m) => m.id === id || m.id === normalized)
}

export function isModuleReady(
  module: ReportModuleDef,
  readiness: Record<string, boolean>
): boolean {
  if (module.requiresAll?.length) {
    if (!module.requiresAll.every((k) => readiness[k])) return false
  }
  return module.requiresAny.some((k) => readiness[k])
}
