/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MiddlewareRouteImport } from './routes/middleware'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth.dashboard.index'
import { Route as AuthDashboardVaultRouteImport } from './routes/_auth.dashboard.vault'
import { Route as AuthDashboardToolsRouteImport } from './routes/_auth.dashboard.tools'
import { Route as AuthDashboardProfileRouteImport } from './routes/_auth.dashboard.profile'
import { Route as AuthDashboardFusionRouteImport } from './routes/_auth.dashboard.fusion'
import { Route as AuthDashboardComplianceRouteImport } from './routes/_auth.dashboard.compliance'
import { Route as AuthDashboardFusionIndexRouteImport } from './routes/_auth.dashboard.fusion.index'
import { Route as AuthDashboardFlowsIndexRouteImport } from './routes/_auth.dashboard.flows.index'
import { Route as AuthDashboardEnrichersIndexRouteImport } from './routes/_auth.dashboard.enrichers.index'
import { Route as AuthDashboardCustomTypesIndexRouteImport } from './routes/_auth.dashboard.custom-types.index'
import { Route as AuthDashboardInvestigationsInvestigationIdRouteImport } from './routes/_auth.dashboard.investigations.$investigationId'
import { Route as AuthDashboardFusionReportsRouteImport } from './routes/_auth.dashboard.fusion.reports'
import { Route as AuthDashboardFusionInvestigateRouteImport } from './routes/_auth.dashboard.fusion.investigate'
import { Route as AuthDashboardFlowsFlowIdRouteImport } from './routes/_auth.dashboard.flows.$flowId'
import { Route as AuthDashboardEnrichersNewRouteImport } from './routes/_auth.dashboard.enrichers.new'
import { Route as AuthDashboardEnrichersEnricherIdRouteImport } from './routes/_auth.dashboard.enrichers.$enricherId'
import { Route as AuthDashboardCustomTypesTypeIdRouteImport } from './routes/_auth.dashboard.custom-types.$typeId'
import { Route as AuthDashboardInvestigationsInvestigationIdIndexRouteImport } from './routes/_auth.dashboard.investigations.$investigationId.index'
import { Route as AuthDashboardFusionReportsIndexRouteImport } from './routes/_auth.dashboard.fusion.reports.index'
import { Route as AuthDashboardFusionReportsCaseRefRouteImport } from './routes/_auth.dashboard.fusion.reports.$caseRef'
import { Route as AuthDashboardFusionInvestigationCaseRefRouteImport } from './routes/_auth.dashboard.fusion.investigation.$caseRef'
import { Route as AuthDashboardFusionReportsCaseRefIndexRouteImport } from './routes/_auth.dashboard.fusion.reports.$caseRef.index'
import { Route as AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport } from './routes/_auth.dashboard.investigations.$investigationId.$type.$id'
import { Route as AuthDashboardFusionReportsCaseRefReportTypeRouteImport } from './routes/_auth.dashboard.fusion.reports.$caseRef.$reportType'
import { Route as AuthDashboardFusionInvestigationCaseRefGraphRouteImport } from './routes/_auth.dashboard.fusion.investigation.$caseRef.graph'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MiddlewareRoute = MiddlewareRouteImport.update({
  id: '/middleware',
  path: '/middleware',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardVaultRoute = AuthDashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardToolsRoute = AuthDashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardProfileRoute = AuthDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardFusionRoute = AuthDashboardFusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardComplianceRoute = AuthDashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardFusionIndexRoute =
  AuthDashboardFusionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardFusionRoute,
  } as any)
const AuthDashboardFlowsIndexRoute = AuthDashboardFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardEnrichersIndexRoute =
  AuthDashboardEnrichersIndexRouteImport.update({
    id: '/enrichers/',
    path: '/enrichers/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardCustomTypesIndexRoute =
  AuthDashboardCustomTypesIndexRouteImport.update({
    id: '/custom-types/',
    path: '/custom-types/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardInvestigationsInvestigationIdRoute =
  AuthDashboardInvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardFusionReportsRoute =
  AuthDashboardFusionReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthDashboardFusionRoute,
  } as any)
const AuthDashboardFusionInvestigateRoute =
  AuthDashboardFusionInvestigateRouteImport.update({
    id: '/investigate',
    path: '/investigate',
    getParentRoute: () => AuthDashboardFusionRoute,
  } as any)
const AuthDashboardFlowsFlowIdRoute =
  AuthDashboardFlowsFlowIdRouteImport.update({
    id: '/flows/$flowId',
    path: '/flows/$flowId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEnrichersNewRoute =
  AuthDashboardEnrichersNewRouteImport.update({
    id: '/enrichers/new',
    path: '/enrichers/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEnrichersEnricherIdRoute =
  AuthDashboardEnrichersEnricherIdRouteImport.update({
    id: '/enrichers/$enricherId',
    path: '/enrichers/$enricherId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardCustomTypesTypeIdRoute =
  AuthDashboardCustomTypesTypeIdRouteImport.update({
    id: '/custom-types/$typeId',
    path: '/custom-types/$typeId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardInvestigationsInvestigationIdIndexRoute =
  AuthDashboardInvestigationsInvestigationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardInvestigationsInvestigationIdRoute,
  } as any)
const AuthDashboardFusionReportsIndexRoute =
  AuthDashboardFusionReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardFusionReportsRoute,
  } as any)
const AuthDashboardFusionReportsCaseRefRoute =
  AuthDashboardFusionReportsCaseRefRouteImport.update({
    id: '/$caseRef',
    path: '/$caseRef',
    getParentRoute: () => AuthDashboardFusionReportsRoute,
  } as any)
const AuthDashboardFusionInvestigationCaseRefRoute =
  AuthDashboardFusionInvestigationCaseRefRouteImport.update({
    id: '/investigation/$caseRef',
    path: '/investigation/$caseRef',
    getParentRoute: () => AuthDashboardFusionRoute,
  } as any)
const AuthDashboardFusionReportsCaseRefIndexRoute =
  AuthDashboardFusionReportsCaseRefIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardFusionReportsCaseRefRoute,
  } as any)
const AuthDashboardInvestigationsInvestigationIdTypeIdRoute =
  AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport.update({
    id: '/$type/$id',
    path: '/$type/$id',
    getParentRoute: () => AuthDashboardInvestigationsInvestigationIdRoute,
  } as any)
const AuthDashboardFusionReportsCaseRefReportTypeRoute =
  AuthDashboardFusionReportsCaseRefReportTypeRouteImport.update({
    id: '/$reportType',
    path: '/$reportType',
    getParentRoute: () => AuthDashboardFusionReportsCaseRefRoute,
  } as any)
const AuthDashboardFusionInvestigationCaseRefGraphRoute =
  AuthDashboardFusionInvestigationCaseRefGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AuthDashboardFusionInvestigationCaseRefRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/compliance': typeof AuthDashboardComplianceRoute
  '/dashboard/fusion': typeof AuthDashboardFusionRouteWithChildren
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/tools': typeof AuthDashboardToolsRoute
  '/dashboard/vault': typeof AuthDashboardVaultRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/dashboard/fusion/investigate': typeof AuthDashboardFusionInvestigateRoute
  '/dashboard/fusion/reports': typeof AuthDashboardFusionReportsRouteWithChildren
  '/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  '/dashboard/custom-types': typeof AuthDashboardCustomTypesIndexRoute
  '/dashboard/enrichers': typeof AuthDashboardEnrichersIndexRoute
  '/dashboard/flows': typeof AuthDashboardFlowsIndexRoute
  '/dashboard/fusion/': typeof AuthDashboardFusionIndexRoute
  '/dashboard/fusion/investigation/$caseRef': typeof AuthDashboardFusionInvestigationCaseRefRouteWithChildren
  '/dashboard/fusion/reports/$caseRef': typeof AuthDashboardFusionReportsCaseRefRouteWithChildren
  '/dashboard/fusion/reports/': typeof AuthDashboardFusionReportsIndexRoute
  '/dashboard/investigations/$investigationId/': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/dashboard/fusion/investigation/$caseRef/graph': typeof AuthDashboardFusionInvestigationCaseRefGraphRoute
  '/dashboard/fusion/reports/$caseRef/$reportType': typeof AuthDashboardFusionReportsCaseRefReportTypeRoute
  '/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
  '/dashboard/fusion/reports/$caseRef/': typeof AuthDashboardFusionReportsCaseRefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/dashboard/compliance': typeof AuthDashboardComplianceRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/tools': typeof AuthDashboardToolsRoute
  '/dashboard/vault': typeof AuthDashboardVaultRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/dashboard/fusion/investigate': typeof AuthDashboardFusionInvestigateRoute
  '/dashboard/custom-types': typeof AuthDashboardCustomTypesIndexRoute
  '/dashboard/enrichers': typeof AuthDashboardEnrichersIndexRoute
  '/dashboard/flows': typeof AuthDashboardFlowsIndexRoute
  '/dashboard/fusion': typeof AuthDashboardFusionIndexRoute
  '/dashboard/fusion/investigation/$caseRef': typeof AuthDashboardFusionInvestigationCaseRefRouteWithChildren
  '/dashboard/fusion/reports': typeof AuthDashboardFusionReportsIndexRoute
  '/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/dashboard/fusion/investigation/$caseRef/graph': typeof AuthDashboardFusionInvestigationCaseRefGraphRoute
  '/dashboard/fusion/reports/$caseRef/$reportType': typeof AuthDashboardFusionReportsCaseRefReportTypeRoute
  '/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
  '/dashboard/fusion/reports/$caseRef': typeof AuthDashboardFusionReportsCaseRefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/compliance': typeof AuthDashboardComplianceRoute
  '/_auth/dashboard/fusion': typeof AuthDashboardFusionRouteWithChildren
  '/_auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/_auth/dashboard/tools': typeof AuthDashboardToolsRoute
  '/_auth/dashboard/vault': typeof AuthDashboardVaultRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/_auth/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/_auth/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/_auth/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/_auth/dashboard/fusion/investigate': typeof AuthDashboardFusionInvestigateRoute
  '/_auth/dashboard/fusion/reports': typeof AuthDashboardFusionReportsRouteWithChildren
  '/_auth/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  '/_auth/dashboard/custom-types/': typeof AuthDashboardCustomTypesIndexRoute
  '/_auth/dashboard/enrichers/': typeof AuthDashboardEnrichersIndexRoute
  '/_auth/dashboard/flows/': typeof AuthDashboardFlowsIndexRoute
  '/_auth/dashboard/fusion/': typeof AuthDashboardFusionIndexRoute
  '/_auth/dashboard/fusion/investigation/$caseRef': typeof AuthDashboardFusionInvestigationCaseRefRouteWithChildren
  '/_auth/dashboard/fusion/reports/$caseRef': typeof AuthDashboardFusionReportsCaseRefRouteWithChildren
  '/_auth/dashboard/fusion/reports/': typeof AuthDashboardFusionReportsIndexRoute
  '/_auth/dashboard/investigations/$investigationId/': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/_auth/dashboard/fusion/investigation/$caseRef/graph': typeof AuthDashboardFusionInvestigationCaseRefGraphRoute
  '/_auth/dashboard/fusion/reports/$caseRef/$reportType': typeof AuthDashboardFusionReportsCaseRefReportTypeRoute
  '/_auth/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
  '/_auth/dashboard/fusion/reports/$caseRef/': typeof AuthDashboardFusionReportsCaseRefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/middleware'
    | '/register'
    | '/dashboard'
    | '/dashboard/compliance'
    | '/dashboard/fusion'
    | '/dashboard/profile'
    | '/dashboard/tools'
    | '/dashboard/vault'
    | '/dashboard/'
    | '/dashboard/custom-types/$typeId'
    | '/dashboard/enrichers/$enricherId'
    | '/dashboard/enrichers/new'
    | '/dashboard/flows/$flowId'
    | '/dashboard/fusion/investigate'
    | '/dashboard/fusion/reports'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/custom-types'
    | '/dashboard/enrichers'
    | '/dashboard/flows'
    | '/dashboard/fusion/'
    | '/dashboard/fusion/investigation/$caseRef'
    | '/dashboard/fusion/reports/$caseRef'
    | '/dashboard/fusion/reports/'
    | '/dashboard/investigations/$investigationId/'
    | '/dashboard/fusion/investigation/$caseRef/graph'
    | '/dashboard/fusion/reports/$caseRef/$reportType'
    | '/dashboard/investigations/$investigationId/$type/$id'
    | '/dashboard/fusion/reports/$caseRef/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/middleware'
    | '/register'
    | '/dashboard/compliance'
    | '/dashboard/profile'
    | '/dashboard/tools'
    | '/dashboard/vault'
    | '/dashboard'
    | '/dashboard/custom-types/$typeId'
    | '/dashboard/enrichers/$enricherId'
    | '/dashboard/enrichers/new'
    | '/dashboard/flows/$flowId'
    | '/dashboard/fusion/investigate'
    | '/dashboard/custom-types'
    | '/dashboard/enrichers'
    | '/dashboard/flows'
    | '/dashboard/fusion'
    | '/dashboard/fusion/investigation/$caseRef'
    | '/dashboard/fusion/reports'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/fusion/investigation/$caseRef/graph'
    | '/dashboard/fusion/reports/$caseRef/$reportType'
    | '/dashboard/investigations/$investigationId/$type/$id'
    | '/dashboard/fusion/reports/$caseRef'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/middleware'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/dashboard/compliance'
    | '/_auth/dashboard/fusion'
    | '/_auth/dashboard/profile'
    | '/_auth/dashboard/tools'
    | '/_auth/dashboard/vault'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/custom-types/$typeId'
    | '/_auth/dashboard/enrichers/$enricherId'
    | '/_auth/dashboard/enrichers/new'
    | '/_auth/dashboard/flows/$flowId'
    | '/_auth/dashboard/fusion/investigate'
    | '/_auth/dashboard/fusion/reports'
    | '/_auth/dashboard/investigations/$investigationId'
    | '/_auth/dashboard/custom-types/'
    | '/_auth/dashboard/enrichers/'
    | '/_auth/dashboard/flows/'
    | '/_auth/dashboard/fusion/'
    | '/_auth/dashboard/fusion/investigation/$caseRef'
    | '/_auth/dashboard/fusion/reports/$caseRef'
    | '/_auth/dashboard/fusion/reports/'
    | '/_auth/dashboard/investigations/$investigationId/'
    | '/_auth/dashboard/fusion/investigation/$caseRef/graph'
    | '/_auth/dashboard/fusion/reports/$caseRef/$reportType'
    | '/_auth/dashboard/investigations/$investigationId/$type/$id'
    | '/_auth/dashboard/fusion/reports/$caseRef/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  MiddlewareRoute: typeof MiddlewareRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware': {
      id: '/middleware'
      path: '/middleware'
      fullPath: '/middleware'
      preLoaderRoute: typeof MiddlewareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/vault': {
      id: '/_auth/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof AuthDashboardVaultRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/tools': {
      id: '/_auth/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof AuthDashboardToolsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/profile': {
      id: '/_auth/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/fusion': {
      id: '/_auth/dashboard/fusion'
      path: '/fusion'
      fullPath: '/dashboard/fusion'
      preLoaderRoute: typeof AuthDashboardFusionRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/compliance': {
      id: '/_auth/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof AuthDashboardComplianceRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/fusion/': {
      id: '/_auth/dashboard/fusion/'
      path: '/'
      fullPath: '/dashboard/fusion/'
      preLoaderRoute: typeof AuthDashboardFusionIndexRouteImport
      parentRoute: typeof AuthDashboardFusionRoute
    }
    '/_auth/dashboard/flows/': {
      id: '/_auth/dashboard/flows/'
      path: '/flows'
      fullPath: '/dashboard/flows'
      preLoaderRoute: typeof AuthDashboardFlowsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/': {
      id: '/_auth/dashboard/enrichers/'
      path: '/enrichers'
      fullPath: '/dashboard/enrichers'
      preLoaderRoute: typeof AuthDashboardEnrichersIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/custom-types/': {
      id: '/_auth/dashboard/custom-types/'
      path: '/custom-types'
      fullPath: '/dashboard/custom-types'
      preLoaderRoute: typeof AuthDashboardCustomTypesIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/investigations/$investigationId': {
      id: '/_auth/dashboard/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/dashboard/investigations/$investigationId'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/fusion/reports': {
      id: '/_auth/dashboard/fusion/reports'
      path: '/reports'
      fullPath: '/dashboard/fusion/reports'
      preLoaderRoute: typeof AuthDashboardFusionReportsRouteImport
      parentRoute: typeof AuthDashboardFusionRoute
    }
    '/_auth/dashboard/fusion/investigate': {
      id: '/_auth/dashboard/fusion/investigate'
      path: '/investigate'
      fullPath: '/dashboard/fusion/investigate'
      preLoaderRoute: typeof AuthDashboardFusionInvestigateRouteImport
      parentRoute: typeof AuthDashboardFusionRoute
    }
    '/_auth/dashboard/flows/$flowId': {
      id: '/_auth/dashboard/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/dashboard/flows/$flowId'
      preLoaderRoute: typeof AuthDashboardFlowsFlowIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/new': {
      id: '/_auth/dashboard/enrichers/new'
      path: '/enrichers/new'
      fullPath: '/dashboard/enrichers/new'
      preLoaderRoute: typeof AuthDashboardEnrichersNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/$enricherId': {
      id: '/_auth/dashboard/enrichers/$enricherId'
      path: '/enrichers/$enricherId'
      fullPath: '/dashboard/enrichers/$enricherId'
      preLoaderRoute: typeof AuthDashboardEnrichersEnricherIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/custom-types/$typeId': {
      id: '/_auth/dashboard/custom-types/$typeId'
      path: '/custom-types/$typeId'
      fullPath: '/dashboard/custom-types/$typeId'
      preLoaderRoute: typeof AuthDashboardCustomTypesTypeIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/investigations/$investigationId/': {
      id: '/_auth/dashboard/investigations/$investigationId/'
      path: '/'
      fullPath: '/dashboard/investigations/$investigationId/'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdIndexRouteImport
      parentRoute: typeof AuthDashboardInvestigationsInvestigationIdRoute
    }
    '/_auth/dashboard/fusion/reports/': {
      id: '/_auth/dashboard/fusion/reports/'
      path: '/'
      fullPath: '/dashboard/fusion/reports/'
      preLoaderRoute: typeof AuthDashboardFusionReportsIndexRouteImport
      parentRoute: typeof AuthDashboardFusionReportsRoute
    }
    '/_auth/dashboard/fusion/reports/$caseRef': {
      id: '/_auth/dashboard/fusion/reports/$caseRef'
      path: '/$caseRef'
      fullPath: '/dashboard/fusion/reports/$caseRef'
      preLoaderRoute: typeof AuthDashboardFusionReportsCaseRefRouteImport
      parentRoute: typeof AuthDashboardFusionReportsRoute
    }
    '/_auth/dashboard/fusion/investigation/$caseRef': {
      id: '/_auth/dashboard/fusion/investigation/$caseRef'
      path: '/investigation/$caseRef'
      fullPath: '/dashboard/fusion/investigation/$caseRef'
      preLoaderRoute: typeof AuthDashboardFusionInvestigationCaseRefRouteImport
      parentRoute: typeof AuthDashboardFusionRoute
    }
    '/_auth/dashboard/fusion/reports/$caseRef/': {
      id: '/_auth/dashboard/fusion/reports/$caseRef/'
      path: '/'
      fullPath: '/dashboard/fusion/reports/$caseRef/'
      preLoaderRoute: typeof AuthDashboardFusionReportsCaseRefIndexRouteImport
      parentRoute: typeof AuthDashboardFusionReportsCaseRefRoute
    }
    '/_auth/dashboard/investigations/$investigationId/$type/$id': {
      id: '/_auth/dashboard/investigations/$investigationId/$type/$id'
      path: '/$type/$id'
      fullPath: '/dashboard/investigations/$investigationId/$type/$id'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport
      parentRoute: typeof AuthDashboardInvestigationsInvestigationIdRoute
    }
    '/_auth/dashboard/fusion/reports/$caseRef/$reportType': {
      id: '/_auth/dashboard/fusion/reports/$caseRef/$reportType'
      path: '/$reportType'
      fullPath: '/dashboard/fusion/reports/$caseRef/$reportType'
      preLoaderRoute: typeof AuthDashboardFusionReportsCaseRefReportTypeRouteImport
      parentRoute: typeof AuthDashboardFusionReportsCaseRefRoute
    }
    '/_auth/dashboard/fusion/investigation/$caseRef/graph': {
      id: '/_auth/dashboard/fusion/investigation/$caseRef/graph'
      path: '/graph'
      fullPath: '/dashboard/fusion/investigation/$caseRef/graph'
      preLoaderRoute: typeof AuthDashboardFusionInvestigationCaseRefGraphRouteImport
      parentRoute: typeof AuthDashboardFusionInvestigationCaseRefRoute
    }
  }
}

interface AuthDashboardFusionReportsCaseRefRouteChildren {
  AuthDashboardFusionReportsCaseRefReportTypeRoute: typeof AuthDashboardFusionReportsCaseRefReportTypeRoute
  AuthDashboardFusionReportsCaseRefIndexRoute: typeof AuthDashboardFusionReportsCaseRefIndexRoute
}

const AuthDashboardFusionReportsCaseRefRouteChildren: AuthDashboardFusionReportsCaseRefRouteChildren =
  {
    AuthDashboardFusionReportsCaseRefReportTypeRoute:
      AuthDashboardFusionReportsCaseRefReportTypeRoute,
    AuthDashboardFusionReportsCaseRefIndexRoute:
      AuthDashboardFusionReportsCaseRefIndexRoute,
  }

const AuthDashboardFusionReportsCaseRefRouteWithChildren =
  AuthDashboardFusionReportsCaseRefRoute._addFileChildren(
    AuthDashboardFusionReportsCaseRefRouteChildren,
  )

interface AuthDashboardFusionReportsRouteChildren {
  AuthDashboardFusionReportsCaseRefRoute: typeof AuthDashboardFusionReportsCaseRefRouteWithChildren
  AuthDashboardFusionReportsIndexRoute: typeof AuthDashboardFusionReportsIndexRoute
}

const AuthDashboardFusionReportsRouteChildren: AuthDashboardFusionReportsRouteChildren =
  {
    AuthDashboardFusionReportsCaseRefRoute:
      AuthDashboardFusionReportsCaseRefRouteWithChildren,
    AuthDashboardFusionReportsIndexRoute: AuthDashboardFusionReportsIndexRoute,
  }

const AuthDashboardFusionReportsRouteWithChildren =
  AuthDashboardFusionReportsRoute._addFileChildren(
    AuthDashboardFusionReportsRouteChildren,
  )

interface AuthDashboardFusionInvestigationCaseRefRouteChildren {
  AuthDashboardFusionInvestigationCaseRefGraphRoute: typeof AuthDashboardFusionInvestigationCaseRefGraphRoute
}

const AuthDashboardFusionInvestigationCaseRefRouteChildren: AuthDashboardFusionInvestigationCaseRefRouteChildren =
  {
    AuthDashboardFusionInvestigationCaseRefGraphRoute:
      AuthDashboardFusionInvestigationCaseRefGraphRoute,
  }

const AuthDashboardFusionInvestigationCaseRefRouteWithChildren =
  AuthDashboardFusionInvestigationCaseRefRoute._addFileChildren(
    AuthDashboardFusionInvestigationCaseRefRouteChildren,
  )

interface AuthDashboardFusionRouteChildren {
  AuthDashboardFusionInvestigateRoute: typeof AuthDashboardFusionInvestigateRoute
  AuthDashboardFusionReportsRoute: typeof AuthDashboardFusionReportsRouteWithChildren
  AuthDashboardFusionIndexRoute: typeof AuthDashboardFusionIndexRoute
  AuthDashboardFusionInvestigationCaseRefRoute: typeof AuthDashboardFusionInvestigationCaseRefRouteWithChildren
}

const AuthDashboardFusionRouteChildren: AuthDashboardFusionRouteChildren = {
  AuthDashboardFusionInvestigateRoute: AuthDashboardFusionInvestigateRoute,
  AuthDashboardFusionReportsRoute: AuthDashboardFusionReportsRouteWithChildren,
  AuthDashboardFusionIndexRoute: AuthDashboardFusionIndexRoute,
  AuthDashboardFusionInvestigationCaseRefRoute:
    AuthDashboardFusionInvestigationCaseRefRouteWithChildren,
}

const AuthDashboardFusionRouteWithChildren =
  AuthDashboardFusionRoute._addFileChildren(AuthDashboardFusionRouteChildren)

interface AuthDashboardInvestigationsInvestigationIdRouteChildren {
  AuthDashboardInvestigationsInvestigationIdIndexRoute: typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  AuthDashboardInvestigationsInvestigationIdTypeIdRoute: typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
}

const AuthDashboardInvestigationsInvestigationIdRouteChildren: AuthDashboardInvestigationsInvestigationIdRouteChildren =
  {
    AuthDashboardInvestigationsInvestigationIdIndexRoute:
      AuthDashboardInvestigationsInvestigationIdIndexRoute,
    AuthDashboardInvestigationsInvestigationIdTypeIdRoute:
      AuthDashboardInvestigationsInvestigationIdTypeIdRoute,
  }

const AuthDashboardInvestigationsInvestigationIdRouteWithChildren =
  AuthDashboardInvestigationsInvestigationIdRoute._addFileChildren(
    AuthDashboardInvestigationsInvestigationIdRouteChildren,
  )

interface AuthDashboardRouteChildren {
  AuthDashboardComplianceRoute: typeof AuthDashboardComplianceRoute
  AuthDashboardFusionRoute: typeof AuthDashboardFusionRouteWithChildren
  AuthDashboardProfileRoute: typeof AuthDashboardProfileRoute
  AuthDashboardToolsRoute: typeof AuthDashboardToolsRoute
  AuthDashboardVaultRoute: typeof AuthDashboardVaultRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardCustomTypesTypeIdRoute: typeof AuthDashboardCustomTypesTypeIdRoute
  AuthDashboardEnrichersEnricherIdRoute: typeof AuthDashboardEnrichersEnricherIdRoute
  AuthDashboardEnrichersNewRoute: typeof AuthDashboardEnrichersNewRoute
  AuthDashboardFlowsFlowIdRoute: typeof AuthDashboardFlowsFlowIdRoute
  AuthDashboardInvestigationsInvestigationIdRoute: typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  AuthDashboardCustomTypesIndexRoute: typeof AuthDashboardCustomTypesIndexRoute
  AuthDashboardEnrichersIndexRoute: typeof AuthDashboardEnrichersIndexRoute
  AuthDashboardFlowsIndexRoute: typeof AuthDashboardFlowsIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardComplianceRoute: AuthDashboardComplianceRoute,
  AuthDashboardFusionRoute: AuthDashboardFusionRouteWithChildren,
  AuthDashboardProfileRoute: AuthDashboardProfileRoute,
  AuthDashboardToolsRoute: AuthDashboardToolsRoute,
  AuthDashboardVaultRoute: AuthDashboardVaultRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardCustomTypesTypeIdRoute: AuthDashboardCustomTypesTypeIdRoute,
  AuthDashboardEnrichersEnricherIdRoute: AuthDashboardEnrichersEnricherIdRoute,
  AuthDashboardEnrichersNewRoute: AuthDashboardEnrichersNewRoute,
  AuthDashboardFlowsFlowIdRoute: AuthDashboardFlowsFlowIdRoute,
  AuthDashboardInvestigationsInvestigationIdRoute:
    AuthDashboardInvestigationsInvestigationIdRouteWithChildren,
  AuthDashboardCustomTypesIndexRoute: AuthDashboardCustomTypesIndexRoute,
  AuthDashboardEnrichersIndexRoute: AuthDashboardEnrichersIndexRoute,
  AuthDashboardFlowsIndexRoute: AuthDashboardFlowsIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  MiddlewareRoute: MiddlewareRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
